const CATALOG = [
 {id:'svj',name:'Lamborghini Aventador SVJ',category:'Машины',price:40000000,image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=700&q=80'},
 {id:'bmw',name:'BMW M5 CS',category:'Машины',price:60000000,image:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=700&q=80'},
 {id:'jesko',name:'Koenigsegg Jesko',category:'Машины',price:120000000,image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=700&q=80'},
 {id:'huayra',name:'Pagani Huayra',category:'Машины',price:155000000,image:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=700&q=80'},
 {id:'divo',name:'Bugatti Divo',price:300000000,category:'Машины',image:'https://images.unsplash.com/photo-1600705722908-bab3c6c8f7b4?auto=format&fit=crop&w=700&q=80'},
 {id:'house',name:'Вилла на Vinewood',price:85000000,category:'Недвижимость',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=700&q=80'},
 {id:'penthouse',name:'Пентхаус Eclipse',price:125000000,category:'Недвижимость',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=700&q=80'},
 {id:'club',name:'Ночной клуб',price:97000000,category:'Бизнесы',image:'https://images.unsplash.com/photo-1566737236500-c8ac43014a8e?auto=format&fit=crop&w=700&q=80'},
 {id:'garage',name:'Автомастерская',price:39000000,category:'Бизнесы',image:'https://images.unsplash.com/photo-1486006920555-c77dcf18193c?auto=format&fit=crop&w=700&q=80'},
 {id:'metal',name:'Редкий металл',price:22000000,category:'Ресурсы',image:'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=700&q=80'},
 {id:'fuel',name:'Контейнер ресурсов',price:9500000,category:'Ресурсы',image:'https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=700&q=80'},
 {id:'chain',name:'Золотая цепь',price:5600000,category:'Аксессуары',image:'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=700&q=80'},
 {id:'watch',name:'Часы Phantom',price:18900000,category:'Аксессуары',image:'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=700&q=80'}
];
const money=n=>Math.round(n).toLocaleString('ru-RU')+' ₽';
const $=id=>document.getElementById(id);
let balance=0, garage=[], selectedBet=null, prize=null, wins=0, losses=0, bestWin=0, history=[], tab='garage', mult=2, uid=1, betMode='item', cashStake=0, activeCategory='Все', spinning=false;
function safeImg(src){return src.replaceAll('&','&amp;').replaceAll('"','&quot;')}
function img(src,cls=''){return `<img class="${cls}" src="${safeImg(src)}" alt="" loading="lazy" onerror="this.onerror=null;this.src='https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=700&q=80'">`}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderFeatured(){
 $('balance').textContent=balance.toLocaleString('ru-RU');$('itemsCount').textContent=garage.length;$('wins').textContent=wins;$('losses').textContent=losses;$('winrate').textContent=(wins+losses?Math.round(wins/(wins+losses)*100):0)+'%';$('bestWin').textContent=money(bestWin);$('progressBar').style.width=(wins+losses?wins/(wins+losses)*100:0)+'%';$('garageValue').textContent=money(garage.reduce((s,x)=>s+x.price,0));
 $('betValue').textContent=betMode==='cash'?money(cashStake):(selectedBet?money(selectedBet.price):'0 ₽');$('betMode').textContent=betMode==='item'?'Наличными':'Предметом';
 $('betContent').innerHTML=betMode==='cash'?`<div class="cash-stake"><label for="cashStake">СУММА СТАВКИ</label><div class="cash-input-wrap"><span class="cash-currency">₽</span><input id="cashStake" type="number" min="1" max="${balance}" step="1" inputmode="numeric" value="${cashStake||''}" placeholder="0"><button type="button" id="maxCash" ${balance>0?'':'disabled'}>MAX</button></div><div class="cash-meta"><small>Доступно на балансе</small><b>${money(balance)}</b></div><small class="cash-hint">Введи сумму, которую готов поставить</small></div>`:selectedBet?`${img(selectedBet.image,'car-img')}<div class="car-name">${selectedBet.name}</div><div class="car-price">${money(selectedBet.price)}</div><div class="car-sub">Предмет для апгрейда</div><div class="chips"><span class="chip">${selectedBet.name}</span></div>`:`<div class="empty-prize" style="height:250px;justify-content:center;color:#666">Инвентарь пуст — выбери режим наличных или купи предмет</div>`;
 $('prizeContent').classList.toggle('empty-prize',!prize);
 $('prizeContent').innerHTML=prize?`${img(prize.image,'car-img')}<div class="car-name">${prize.name}</div><div class="car-price">${money(prize.price)}</div><div class="car-sub">Целевой приз</div><div class="chips"><span class="chip">Чистая прибыль: ${money(Math.max(0,prize.price-(selectedBet?.price||0)))}</span><button class="chip" id="removePrize">Снять выбор ×</button></div>`:`<button class="choose-prize" id="choosePrize"><span>＋</span><b>Выбрать предмет</b><small>Из каталога автомобилей</small></button>`;
 const stakeValue=betMode==='cash'?cashStake:(selectedBet?.price||0);const validStake=stakeValue>0&&(betMode==='cash'?cashStake<=balance:!!selectedBet);const chanceValue=prize&&validStake?Math.min(95,stakeValue/prize.price*100):0;$('chance').textContent=chanceValue.toFixed(2)+'%';$('multLabel').textContent=prize&&validStake?'×'+(prize.price/stakeValue).toFixed(2):'—';$('spin').disabled=!(validStake&&prize&&!spinning);$('spin').classList.toggle('ready',!!(validStake&&prize&&!spinning));$('gameNote').textContent=prize&&validStake?`За ставку ${money(stakeValue)} шанс получить ${prize.name} — ${chanceValue.toFixed(2)}%`:'Выбери ставку и желаемый приз';
 $('choosePrize')?.addEventListener('click',openModal);$('removePrize')?.addEventListener('click',()=>{prize=null;renderAll()});
}
function refreshCashStake(){
 const input=$('cashStake');
 if(input){input.classList.toggle('invalid',cashStake>balance);}
 $('betValue').textContent=betMode==='cash'?money(cashStake):(selectedBet?money(selectedBet.price):'0 ₽');
 const stakeValue=betMode==='cash'?cashStake:(selectedBet?.price||0);
 const validStake=stakeValue>0&&(betMode==='cash'?cashStake<=balance:!!selectedBet);
 const chanceValue=prize&&validStake?Math.min(95,stakeValue/prize.price*100):0;
 $('chance').textContent=chanceValue.toFixed(2)+'%';
 $('multLabel').textContent=prize&&validStake?'×'+(prize.price/stakeValue).toFixed(2):'—';
 $('spin').disabled=!(validStake&&prize&&!spinning);
 $('spin').classList.toggle('ready',!!(validStake&&prize&&!spinning));
 $('gameNote').textContent=prize&&validStake?`За ставку ${money(stakeValue)} шанс получить ${prize.name} — ${chanceValue.toFixed(2)}%`:'Выбери ставку и желаемый приз';
}
function card(item,mode){const selected=mode==='garage'&&selectedBet?.uid===item.uid;const stakeValue=betMode==='cash'?cashStake:(selectedBet?.price||0);const odds=mode==='catalog'&&stakeValue>0?(Math.min(95,stakeValue/item.price*100)).toFixed(1)+'%':'';return `<div class="item-card ${selected?'selected':''}" data-id="${item.id}" data-uid="${item.uid||''}" data-mode="${mode}">${mode==='catalog'&&odds?`<span class="odds">${odds}</span>`:''}${selected?'<span class="check">✓</span>':''}${img(item.image)}<b>${item.name}</b><small class="item-category">${item.category||'Машины'}</small><strong>${money(item.price)}</strong><div class="item-actions">${mode==='garage'?`<button class="primary" data-action="bet">В ставку</button><button data-action="sell">Продать</button>`:`<button class="primary" data-action="prize">Выбрать приз</button><button data-action="buy">Купить</button>`}</div></div>`}
function renderGarage(){const q=$('garageSearch').value.toLowerCase();const items=garage.filter(x=>x.name.toLowerCase().includes(q));$('garageGrid').innerHTML=items.length?items.map(x=>card(x,tab==='sale'?'sale':'garage')).join(''):'<div class="empty-grid">Ничего не найдено</div>';}
function renderCatalog(){let items=[...CATALOG];const q=$('catalogSearch').value.toLowerCase();items=items.filter(x=>(activeCategory==='Все'||(x.category||'Машины')===activeCategory)&&x.name.toLowerCase().includes(q));if($('sort').value==='price-asc')items.sort((a,b)=>a.price-b.price);if($('sort').value==='price-desc')items.sort((a,b)=>b.price-a.price);if($('sort').value==='chance')items.sort((a,b)=>(selectedBet?Math.abs(selectedBet.price/a.price-selectedBet.price/b.price):0));$('catalogGrid').innerHTML=items.map(x=>card(x,'catalog')).join('');}
function renderModal(){const q=$('modalSearch').value.toLowerCase();$('modalGrid').innerHTML=CATALOG.filter(x=>x.name.toLowerCase().includes(q)).map(x=>card(x,'modal')).join('')}
function renderHistory(){$('history').innerHTML=history.length?history.slice(0,5).map(h=>`<div class="history-row">${img(h.item.image)}<div><b>${h.win?'Успешный апгрейд':'Неудача'} · ${h.item.name}</b><small>${h.betName} · ставка ${money(h.betPrice)}</small></div><strong style="color:${h.win?'var(--green)':'var(--red)'}">${h.win?'+'+money(h.item.price):'−'+money(h.betPrice)}</strong></div>`).join(''):'<div class="history-empty">Здесь появятся результаты апгрейдов</div>'}
function renderAll(){renderFeatured();renderGarage();renderCatalog();renderHistory()}
function openModal(){$('modal').classList.add('open');renderModal()}function closeModal(){$('modal').classList.remove('open')}
function buy(item){if(balance<item.price){toast('Недостаточно средств на балансе');return}balance-=item.price;garage.push({...item,uid:uid++});toast('Автомобиль добавлен в гараж');renderAll()}
function sell(uidVal){const i=garage.findIndex(x=>x.uid===Number(uidVal));if(i<0)return;const item=garage[i];garage.splice(i,1);balance+=item.price;if(selectedBet?.uid===item.uid)selectedBet=null;toast(`${item.name} продан за ${money(item.price)}`);renderAll()}
function handleGrid(e){const action=e.target.closest('[data-action]');const el=e.target.closest('.item-card');if(!el)return;const mode=el.dataset.mode,id=el.dataset.id,uidVal=el.dataset.uid;const item=mode==='garage'||mode==='sale'?garage.find(x=>x.uid===Number(uidVal)):CATALOG.find(x=>x.id===id);if(!item)return;if(!action){if(mode==='garage'||mode==='sale'){selectedBet=item;renderAll()}else if(mode==='modal'){prize=item;closeModal();renderAll()}return}switch(action.dataset.action){case'bet':selectedBet=item;renderAll();break;case'sell':sell(uidVal);break;case'prize':prize=item;closeModal();renderAll();toast('Приз выбран — покупка не выполнена');break;case'buy':buy(item);break}}
$('garageGrid').addEventListener('click',handleGrid);$('catalogGrid').addEventListener('click',handleGrid);$('modalGrid').addEventListener('click',handleGrid);
$('choosePrize').addEventListener('click',openModal);$('closeModal').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('modalSearch').addEventListener('input',renderModal);
$('betContent').addEventListener('input',e=>{if(e.target.id!=='cashStake')return;cashStake=Math.max(0,Math.floor(Number(e.target.value)||0));refreshCashStake();renderCatalog()});
$('betContent').addEventListener('click',e=>{if(e.target.id==='maxCash'){cashStake=balance;const input=$('cashStake');if(input)input.value=String(cashStake||'');refreshCashStake();renderCatalog()}});
$('betMode').addEventListener('click',()=>{betMode=betMode==='item'?'cash':'item';if(betMode==='cash')selectedBet=null;renderAll();if(betMode==='cash')setTimeout(()=>$('cashStake')?.focus(),0);toast(betMode==='cash'?'Режим наличных: введи сумму ставки':'Режим предмета: выбери предмет из гаража')});
$('garageSearch').addEventListener('input',renderGarage);$('catalogSearch').addEventListener('input',renderCatalog);$('sort').addEventListener('change',renderCatalog);
document.querySelectorAll('.category-tab').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;document.querySelectorAll('.category-tab').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()}));
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;document.querySelectorAll('.category-tab').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;document.querySelectorAll('.category-tab').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()}));
document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));renderGarage()}));
document.querySelectorAll('[data-mult]').forEach(b=>b.addEventListener('click',()=>{mult=Number(b.dataset.mult);document.querySelectorAll('[data-mult]').forEach(x=>x.classList.toggle('active',x===b));if(selectedBet){const target=CATALOG.find(x=>Math.abs(x.price/selectedBet.price-mult)<.65);if(target)prize=target}renderAll()}));
$('clearBet').addEventListener('click',()=>{if(betMode==='cash'){cashStake=0}else selectedBet=null;renderAll()});$('clearHistory').addEventListener('click',()=>{history=[];renderHistory()});$('topUp').addEventListener('click',()=>{const amount=prompt('Сколько демо-рублей добавить на баланс?', '1000000');if(amount===null)return;const n=Number(amount);if(!Number.isFinite(n)||n<=0){toast('Введи корректную сумму');return}balance+=Math.floor(n);renderAll();toast('Демо-баланс пополнен')});$('addCar').addEventListener('click',()=>openModal());$('reset').addEventListener('click',()=>{balance=0;garage=[];selectedBet=null;prize=null;cashStake=0;betMode='item';wins=0;losses=0;bestWin=0;history=[];uid=1;renderAll();toast('Сессия сброшена: баланс 0, гараж пуст')});
$('spin').addEventListener('click',()=>{const stakeValue=betMode==='cash'?cashStake:(selectedBet?.price||0);if(!prize||stakeValue<=0||spinning)return;if(betMode==='cash'&&stakeValue>balance){toast('Недостаточно денег на балансе');return}if(betMode==='item'&&!selectedBet)return;spinning=true;const ring=document.querySelector('.chance-ring');ring?.classList.remove('is-spinning');void ring?.offsetWidth;ring?.classList.add('is-spinning');$('spin').disabled=true;$('spin').textContent='Крутится…';$('gameNote').textContent='Колесо вращается…';const bet=selectedBet,target=prize,won=Math.random()<Math.min(.95,stakeValue/target.price);if(betMode==='cash')balance-=stakeValue;setTimeout(()=>{ring?.classList.remove('is-spinning');spinning=false;if(won){if(betMode==='item')garage=garage.filter(x=>x.uid!==bet.uid);garage.push({...target,uid:uid++});wins++;bestWin=Math.max(bestWin,target.price);toast('🎉 ПОБЕДА! Приз добавлен в гараж');celebrate()}else{if(betMode==='item')garage=garage.filter(x=>x.uid!==bet.uid);losses++;toast('Неудача — ставка потеряна')}history.unshift({win:won,item:target,betName:betMode==='cash'?'Наличные':bet.name,betPrice:stakeValue});selectedBet=null;cashStake=0;$('spin').textContent='Прокрутить';renderAll()},2600)});

function celebrate(){const layer=document.createElement('div');layer.className='confetti-layer';for(let i=0;i<90;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.animationDelay=Math.random()*.8+'s';p.style.setProperty('--drift',(Math.random()*220-110)+'px');layer.appendChild(p)}document.body.appendChild(layer);setTimeout(()=>layer.remove(),3500)}
renderAll();
