const CATALOG = [
 {id:'svj',name:'Lamborghini Aventador SVJ',price:40000000,image:'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=700&q=80'},
 {id:'bmw',name:'BMW M5 CS',price:60000000,image:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=700&q=80'},
 {id:'jesko',name:'Koenigsegg Jesko',price:120000000,image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=700&q=80'},
 {id:'huayra',name:'Pagani Huayra',price:155000000,image:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=700&q=80'},
 {id:'divo',name:'Bugatti Divo',price:300000000,image:'https://images.unsplash.com/photo-1600705722908-bab3c6c8f7b4?auto=format&fit=crop&w=700&q=80'}
];
const money=n=>Math.round(n).toLocaleString('ru-RU')+' ₽';
const $=id=>document.getElementById(id);
let balance=0, garage=[{...CATALOG[0],uid:1},{...CATALOG[1],uid:2}], selectedBet=null, prize=null, wins=0, losses=0, bestWin=0, history=[], tab='garage', mult=2, uid=3;
function safeImg(src){return src.replaceAll('&','&amp;').replaceAll('"','&quot;')}
function img(src,cls=''){return `<img class="${cls}" src="${safeImg(src)}" alt="" loading="lazy" onerror="this.onerror=null;this.src='https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=700&q=80'">`}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function renderFeatured(){
 $('balance').textContent=balance.toLocaleString('ru-RU');$('itemsCount').textContent=garage.length;$('wins').textContent=wins;$('losses').textContent=losses;$('winrate').textContent=(wins+losses?Math.round(wins/(wins+losses)*100):0)+'%';$('bestWin').textContent=money(bestWin);$('progressBar').style.width=(wins+losses?wins/(wins+losses)*100:0)+'%';$('garageValue').textContent=money(garage.reduce((s,x)=>s+x.price,0));
 $('betValue').textContent=selectedBet?money(selectedBet.price):'0 ₽';
 $('betContent').innerHTML=selectedBet?`${img(selectedBet.image,'car-img')}<div class="car-name">${selectedBet.name}</div><div class="car-price">${money(selectedBet.price)}</div><div class="car-sub">Предмет для апгрейда</div><div class="chips"><span class="chip">${selectedBet.name}</span></div>`:`<div class="empty-prize" style="height:250px;justify-content:center;color:#666">Выбери предмет в гараже</div>`;
 $('prizeContent').classList.toggle('empty-prize',!prize);
 $('prizeContent').innerHTML=prize?`${img(prize.image,'car-img')}<div class="car-name">${prize.name}</div><div class="car-price">${money(prize.price)}</div><div class="car-sub">Целевой приз</div><div class="chips"><span class="chip">Чистая прибыль: ${money(Math.max(0,prize.price-(selectedBet?.price||0)))}</span><button class="chip" id="removePrize">Снять выбор ×</button></div>`:`<button class="choose-prize" id="choosePrize"><span>＋</span><b>Выбрать предмет</b><small>Из каталога автомобилей</small></button>`;
 $('chance').textContent=selectedBet&&prize?Math.min(95,selectedBet.price/prize.price*100).toFixed(2)+'%':'0.00%';$('multLabel').textContent=prize&&selectedBet?'×'+(prize.price/selectedBet.price).toFixed(2):'—';$('spin').disabled=!(selectedBet&&prize);$('spin').classList.toggle('ready',!!(selectedBet&&prize));$('gameNote').textContent=selectedBet&&prize?'Шанс рассчитан от стоимости предметов':'Выбери ставку и желаемый приз';
 $('choosePrize')?.addEventListener('click',openModal);$('removePrize')?.addEventListener('click',()=>{prize=null;renderAll()});
}
function card(item,mode){const selected=mode==='garage'&&selectedBet?.uid===item.uid;const odds=mode==='catalog'&&selectedBet&&prize?(selectedBet.price/item.price*100).toFixed(1)+'%':'';return `<div class="item-card ${selected?'selected':''}" data-id="${item.id}" data-uid="${item.uid||''}" data-mode="${mode}">${mode==='catalog'&&odds?`<span class="odds">${odds}</span>`:''}${selected?'<span class="check">✓</span>':''}${img(item.image)}<b>${item.name}</b><strong>${money(item.price)}</strong><div class="item-actions">${mode==='garage'?`<button class="primary" data-action="bet">В ставку</button><button data-action="sell">Продать</button>`:`<button class="primary" data-action="prize">Выбрать приз</button><button data-action="buy">Купить</button>`}</div></div>`}
function renderGarage(){const q=$('garageSearch').value.toLowerCase();const items=garage.filter(x=>x.name.toLowerCase().includes(q));$('garageGrid').innerHTML=items.length?items.map(x=>card(x,tab==='sale'?'sale':'garage')).join(''):'<div class="empty-grid">Ничего не найдено</div>';}
function renderCatalog(){let items=[...CATALOG];const q=$('catalogSearch').value.toLowerCase();items=items.filter(x=>x.name.toLowerCase().includes(q));if($('sort').value==='price-asc')items.sort((a,b)=>a.price-b.price);if($('sort').value==='price-desc')items.sort((a,b)=>b.price-a.price);if($('sort').value==='chance')items.sort((a,b)=>(selectedBet?Math.abs(selectedBet.price/a.price-selectedBet.price/b.price):0));$('catalogGrid').innerHTML=items.map(x=>card(x,'catalog')).join('');}
function renderModal(){const q=$('modalSearch').value.toLowerCase();$('modalGrid').innerHTML=CATALOG.filter(x=>x.name.toLowerCase().includes(q)).map(x=>card(x,'modal')).join('')}
function renderHistory(){$('history').innerHTML=history.length?history.slice(0,5).map(h=>`<div class="history-row">${img(h.item.image)}<div><b>${h.win?'Успешный апгрейд':'Неудача'} · ${h.item.name}</b><small>${h.betName} · ставка ${money(h.betPrice)}</small></div><strong style="color:${h.win?'var(--green)':'var(--red)'}">${h.win?'+'+money(h.item.price):'−'+money(h.betPrice)}</strong></div>`).join(''):'<div class="history-empty">Здесь появятся результаты апгрейдов</div>'}
function renderAll(){renderFeatured();renderGarage();renderCatalog();renderHistory()}
function openModal(){$('modal').classList.add('open');renderModal()}function closeModal(){$('modal').classList.remove('open')}
function buy(item){if(balance<item.price){toast('Недостаточно средств на балансе');return}balance-=item.price;garage.push({...item,uid:uid++});toast('Автомобиль добавлен в гараж');renderAll()}
function sell(uidVal){const i=garage.findIndex(x=>x.uid===Number(uidVal));if(i<0)return;const item=garage[i];garage.splice(i,1);balance+=item.price;if(selectedBet?.uid===item.uid)selectedBet=null;toast(`${item.name} продан за ${money(item.price)}`);renderAll()}
function handleGrid(e){const action=e.target.closest('[data-action]');const el=e.target.closest('.item-card');if(!el)return;const mode=el.dataset.mode,id=el.dataset.id,uidVal=el.dataset.uid;const item=mode==='garage'||mode==='sale'?garage.find(x=>x.uid===Number(uidVal)):CATALOG.find(x=>x.id===id);if(!item)return;if(!action){if(mode==='garage'||mode==='sale'){selectedBet=item;renderAll()}else if(mode==='modal'){prize=item;closeModal();renderAll()}return}switch(action.dataset.action){case'bet':selectedBet=item;renderAll();break;case'sell':sell(uidVal);break;case'prize':prize=item;closeModal();renderAll();toast('Приз выбран — покупка не выполнена');break;case'buy':buy(item);break}}
$('garageGrid').addEventListener('click',handleGrid);$('catalogGrid').addEventListener('click',handleGrid);$('modalGrid').addEventListener('click',handleGrid);
$('choosePrize').addEventListener('click',openModal);$('closeModal').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('modalSearch').addEventListener('input',renderModal);$('garageSearch').addEventListener('input',renderGarage);$('catalogSearch').addEventListener('input',renderCatalog);$('sort').addEventListener('change',renderCatalog);
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));renderGarage()}));
document.querySelectorAll('[data-mult]').forEach(b=>b.addEventListener('click',()=>{mult=Number(b.dataset.mult);document.querySelectorAll('[data-mult]').forEach(x=>x.classList.toggle('active',x===b));if(selectedBet){const target=CATALOG.find(x=>Math.abs(x.price/selectedBet.price-mult)<.65);if(target)prize=target}renderAll()}));
$('clearBet').addEventListener('click',()=>{selectedBet=null;renderAll()});$('clearHistory').addEventListener('click',()=>{history=[];renderHistory()});$('topUp').addEventListener('click',()=>{const amount=prompt('Сколько демо-рублей добавить на баланс?', '1000000');if(amount===null)return;const n=Number(amount);if(!Number.isFinite(n)||n<=0){toast('Введи корректную сумму');return}balance+=Math.floor(n);renderAll();toast('Демо-баланс пополнен')});$('addCar').addEventListener('click',()=>openModal());$('reset').addEventListener('click',()=>{if(!confirm('Сбросить баланс, гараж и статистику?'))return;balance=0;garage=[{...CATALOG[0],uid:1},{...CATALOG[1],uid:2}];selectedBet=null;prize=null;wins=0;losses=0;bestWin=0;history=[];uid=3;renderAll();toast('Демо-сессия сброшена')});
$('spin').addEventListener('click',()=>{if(!selectedBet||!prize)return;const chance=Math.min(.95,selectedBet.price/prize.price);$('spin').disabled=true;$('spin').textContent='Крутится…';$('gameNote').textContent='Определяем результат…';setTimeout(()=>{const won=Math.random()<chance;const bet=selectedBet;const target=prize;if(won){garage=garage.filter(x=>x.uid!==bet.uid);garage.push({...target,uid:uid++});wins++;bestWin=Math.max(bestWin,target.price);selectedBet=null;toast('Успех! Приз добавлен в гараж')}else{garage=garage.filter(x=>x.uid!==bet.uid);losses++;selectedBet=null;toast('Неудача — ставка потеряна')}history.unshift({win:won,item:target,betName:bet.name,betPrice:bet.price});$('spin').textContent='Прокрутить';renderAll()},950)});
renderAll();
